-- MySQL Script generated by MySQL Workbench
-- Sat Jul 19 16:38:57 2025
-- Model: Sakila Full    Version: 2.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sakila
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sakila
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sakila` ;
USE `sakila` ;

-- -----------------------------------------------------
-- Table `sakila`.`clienti`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sakila`.`clienti` ;

CREATE TABLE IF NOT EXISTS `sakila`.`clienti` (
  `id_cliente` SMALLINT UNSIGNED NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `E-mail` VARCHAR(45) NOT NULL,
  `numero_tel` VARCHAR(45) NOT NULL,
  `indirizzo` VARCHAR(45) NOT NULL,
  `codiceF` VARCHAR(45) NULL,
  `PartitaIva` VARCHAR(45) NULL,
  `tipocliente` ENUM('Privato', 'Servizio Publico') NOT NULL,
  PRIMARY KEY (`id_cliente`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sakila`.`prestiti`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sakila`.`prestiti` ;

CREATE TABLE IF NOT EXISTS `sakila`.`prestiti` (
  `idprestito` INT NOT NULL,
  `DataInizio` DATE NOT NULL,
  `clienti_id_cliente` SMALLINT UNSIGNED NOT NULL,
  `DataFine` DATE NOT NULL,
  `DataRestituzione` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idprestito`, `clienti_id_cliente`),
  INDEX `fk_prestiti_clienti1_idx` (`clienti_id_cliente` ASC),
  CONSTRAINT `fk_prestiti_clienti1`
    FOREIGN KEY (`clienti_id_cliente`)
    REFERENCES `sakila`.`clienti` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sakila`.`Autori`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sakila`.`Autori` ;

CREATE TABLE IF NOT EXISTS `sakila`.`Autori` (
  `idAutori` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Nazionalità` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAutori`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sakila`.`Libri`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sakila`.`Libri` ;

CREATE TABLE IF NOT EXISTS `sakila`.`Libri` (
  `CodiceLibro` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Edizione` VARCHAR(45) NOT NULL,
  `Anno` YEAR(4) NOT NULL,
  `prestiti_idprestito` INT NOT NULL,
  `prestiti_clienti_id_cliente` SMALLINT UNSIGNED NOT NULL,
  `Autori_idAutori` INT NOT NULL,
  `CostoPrestito` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CodiceLibro`, `prestiti_idprestito`, `prestiti_clienti_id_cliente`, `Autori_idAutori`),
  INDEX `fk_Libri_prestiti1_idx` (`prestiti_idprestito` ASC, `prestiti_clienti_id_cliente` ASC),
  INDEX `fk_Libri_Autori1_idx` (`Autori_idAutori` ASC),
  CONSTRAINT `fk_Libri_prestiti1`
    FOREIGN KEY (`prestiti_idprestito` , `prestiti_clienti_id_cliente`)
    REFERENCES `sakila`.`prestiti` (`idprestito` , `clienti_id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Libri_Autori1`
    FOREIGN KEY (`Autori_idAutori`)
    REFERENCES `sakila`.`Autori` (`idAutori`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sakila`.`Settori`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sakila`.`Settori` ;

CREATE TABLE IF NOT EXISTS `sakila`.`Settori` (
  `idSettore` INT NOT NULL,
  `Genere` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idSettore`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sakila`.`Collocati`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sakila`.`Collocati` ;

CREATE TABLE IF NOT EXISTS `sakila`.`Collocati` (
  `Posizione` VARCHAR(45) NOT NULL,
  `Numero_copie` VARCHAR(45) NOT NULL,
  `Disponibilità` TINYINT(1) NOT NULL,
  `Settori_idSettore` INT NOT NULL,
  `Libri_CodiceLibro` INT NOT NULL,
  PRIMARY KEY (`Settori_idSettore`, `Libri_CodiceLibro`),
  INDEX `fk_Collocati_Settori1_idx` (`Settori_idSettore` ASC),
  INDEX `fk_Collocati_Libri1_idx` (`Libri_CodiceLibro` ASC),
  CONSTRAINT `fk_Collocati_Settori1`
    FOREIGN KEY (`Settori_idSettore`)
    REFERENCES `sakila`.`Settori` (`idSettore`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Collocati_Libri1`
    FOREIGN KEY (`Libri_CodiceLibro`)
    REFERENCES `sakila`.`Libri` (`CodiceLibro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sakila`.`ritardi`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sakila`.`ritardi` ;

CREATE TABLE IF NOT EXISTS `sakila`.`ritardi` (
  `idritardi` INT NOT NULL,
  `prestiti_idprestito` INT NOT NULL,
  `prestiti_clienti_id_cliente` SMALLINT UNSIGNED NOT NULL,
  `penale` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idritardi`, `prestiti_idprestito`, `prestiti_clienti_id_cliente`),
  INDEX `fk_ritardi_prestiti1_idx` (`prestiti_idprestito` ASC, `prestiti_clienti_id_cliente` ASC),
  CONSTRAINT `fk_ritardi_prestiti1`
    FOREIGN KEY (`prestiti_idprestito` , `prestiti_clienti_id_cliente`)
    REFERENCES `sakila`.`prestiti` (`idprestito` , `clienti_id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `sakila` ;

-- -----------------------------------------------------
-- Placeholder table for view `sakila`.`disponibilità`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sakila`.`disponibilità` (`codicelibro` INT);

-- -----------------------------------------------------
-- View `sakila`.`disponibilità`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sakila`.`disponibilità`;
DROP VIEW IF EXISTS `sakila`.`disponibilità` ;
USE `sakila`;
CREATE  OR REPLACE VIEW `disponibilità` AS
SELECT libri.codicelibro FROM libri join collocati
where collocati.disponibilità = 0;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
